Repository Mashiepotatoes/SurpriseMe, pull requests merged in 2021-09, with the labels that each got.

#2 category model created
  Gemfile.lock
  app/models/category.rb
  db/migrate/20210922031952_create_categories.rb
  db/schema.rb
  test/models/category_test.rb
Labels: enhancement

#3 products model created
  app/models/product.rb
  db/migrate/20210922035821_create_products.rb
  db/schema.rb
  test/models/product_test.rb
Labels: enhancement

#4 occasions model created
  Gemfile.lock
  app/models/occasion.rb
  db/migrate/20210922040545_create_occasions.rb
  db/schema.rb
  test/models/occasion_test.rb
Labels: enhancement

#5 added details column
  db/migrate/20210922063241_add_details_to_product.rb
  db/schema.rb
Labels: enhancement

#6 setup devise controller
  Gemfile
  Gemfile.lock
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/users/confirmations/new.html.erb
  app/views/users/mailer/confirmation_instructions.html.erb
  app/views/users/mailer/email_changed.html.erb
  app/views/users/mailer/password_change.html.erb
  app/views/users/mailer/reset_password_instructions.html.erb
  app/views/users/mailer/unlock_instructions.html.erb
  app/views/users/passwords/edit.html.erb
  app/views/users/passwords/new.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/new.html.erb
  app/views/users/sessions/new.html.erb
  app/views/users/shared/_error_messages.html.erb
  app/views/users/shared/_links.html.erb
  app/views/users/unlocks/new.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20210922061247_devise_create_users.rb
  db/migrate/20210922062347_add_birthday_address_to_users.rb
  db/migrate/20210922062735_add_username_to_users.rb
  db/schema.rb
  test/models/user_test.rb
Labels: enhancement

#7 Feature seeding
  Gemfile.lock
  db/seeds.rb
Labels: enhancement

#8 friends list controller
  Gemfile.lock
  app/controllers/friends_list_controller.rb
  config/routes.rb
  test/controllers/friends_list_controller_test.rb
Labels: enhancement

#9 friends list index
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_friendslist.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_search_bar.scss
  app/controllers/friends_list_controller.rb
  app/views/friends_list/index.html.erb
  db/schema.rb
Labels: enhancement

#11 added friends list display
  app/assets/stylesheets/components/_card_product.scss
  app/assets/stylesheets/components/_friend.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_search_bar.scss
  app/views/friends_list/index.html.erb
Labels: enhancement

#10 Profile page
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_user_card.scss
  app/views/friend_show.html.erb
Labels: enhancement

#12 Adding friend
  app/assets/stylesheets/components/_user_card.scss
  app/views/show.html.erb
  db/seeds.rb
Labels: enhancement

#13 Feat friends send gift button
  app/assets/stylesheets/components/_index.scss
  app/controllers/friends_controller.rb
  app/controllers/friends_list_controller.rb
  app/views/friends/index.html.erb
  app/views/friends/show.html.erb
  app/views/friends_list/index.html.erb
  config/routes.rb
Labels: enhancement

#14 Gift reco model controller
  app/controllers/gift_recommendations_controller.rb
  app/models/gift_recommendation.rb
  app/views/gift_recommendations/index.html.erb
  config/routes.rb
  db/migrate/20210923061616_create_gift_recommendations.rb
  db/schema.rb
  test/controllers/gift_recommendations_controller_test.rb
  test/models/gift_recommendation_test.rb
Labels: enhancement

#15 Add product and user seeds
  , 
  Gemfile
  Gemfile.lock
  app/models/category.rb
  db/amazon_datasets/all_beauty.json
  db/amazon_datasets/cd_vinyl.json
  db/amazon_datasets/pet_supplies.json
  db/amazon_datasets/toys_games.json
  db/amazon_datasets/video_games.json
  db/migrate/20210922085018_change_column_name_products_details.rb
  db/migrate/20210922085822_add_columns_to_products.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#18 added send gift button
  app/assets/stylesheets/components/_button.scss
  app/views/friends/show.html.erb
Labels: enhancement

#19 send,view,accept friend request feature
  app/controllers/friendships_controller.rb
  app/models/friendship.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/friendships/index.html.erb
  app/views/pages/home.html.erb
  config/routes.rb
  db/migrate/20210923045811_create_friendships.rb
  db/migrate/20210923064658_add_status_to_friendship.rb
  db/migrate/20210923065325_add_default_value_to_friendship.rb
  db/schema.rb
  test/models/friendship_test.rb
Labels: enhancement

#20 Amend order model
  db/migrate/20210923103639_add_reference_to_orders.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#21 Create order seeds
  app/models/review.rb
  db/amazon_datasets/cd_vinyl.json
  db/amazon_datasets/toys_games.json
  db/migrate/20210923162952_drop_reviews.rb
  db/migrate/20210923163113_create_reviews.rb
  db/schema.rb
  db/seeds.rb
  test/models/review_test.rb
Labels: enhancement

#22 Link session to gift recommendation
  Gemfile
  app/controllers/gift_recommendations_controller.rb
  app/controllers/sessions_controller.rb
  app/models/gift_recommendation.rb
  app/models/session.rb
  app/views/friendships/show.html.erb
  app/views/sessions/new.html.erb
  app/views/sessions/show.html.erb
  config/routes.rb
Labels: enhancement

#23 Friend page
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components/_card_product.scss
  app/assets/stylesheets/components/_friend.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/pages/_friend_index.scss
  app/assets/stylesheets/pages/_friend_request.scss
  app/assets/stylesheets/pages/_index.scss
  app/controllers/friendships_controller.rb
  app/models/user.rb
  app/views/friendships/index.html.erb
  app/views/friendships/requests.html.erb
  app/views/friendships/search.html.erb
  app/views/pages/home.html.erb
  config/routes.rb
  db/schema.rb
Labels: enhancement

#25 Feat cart
  Gemfile
  app/controllers/application_controller.rb
  app/controllers/gift_sessions_controller.rb
  app/controllers/sessions_controller.rb
  app/models/gift_session.rb
  app/views/friendships/show.html.erb
  app/views/gift_sessions/create.html.erb
  app/views/gift_sessions/new.html.erb
  app/views/gift_sessions/show.html.erb
  app/views/sessions/show.html.erb
  config/routes.rb
  db/__schema.rb
  db/migrate/20210923162952_drop_reviews.rb
  db/migrate/20210924065121_create_carts.rb
  db/migrate/20210924073421_change_sessions_to_gift_sessions.rb
  db/schema.rb
  db/seeds.rb
  test/models/cart_test.rb
Labels: bug

#24 integrate typeform button
  app/views/friendships/index.html.erb
  config/routes.rb
  db/schema.rb
Labels: enhancement

#26 complete send gift flow
  app/controllers/friendships_controller.rb
  app/views/friendships/index.html.erb
  app/views/friendships/search.html.erb
  app/views/friendships/show.html.erb
  config/routes.rb
  db/schema.rb
Labels: enhancement

#27 Fix add friend feat
  Gemfile
  Gemfile.lock
  app/models/gift_recommendation.rb
  app/views/friendships/show.html.erb
  db/migrate/20210924085543_rename_foreign_key_for_gift_reccomendations.rb
  db/migrate/20210924091216_add_foreign_key_for_gift_reccomendations.rb
  db/schema.rb
  db/seeds.rb
Labels: bug

#28 add necessary(birthday,first&last name,address) params to application…
  app/controllers/application_controller.rb
Labels: enhancement

#29 sign up page and flash notice
  app/assets/stylesheets/components/_alert.scss
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_colors.scss
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  app/views/layouts/_messages.html.erb
  app/views/layouts/application.html.erb
  db/migrate/20210924145158_add_first_last_name_to_user.rb
  db/schema.rb
Labels: enhancement

#30 Gift Recommendation Show Page
  app/assets/stylesheets/components/_gift_card.scss
  app/assets/stylesheets/components/_index.scss
  app/controllers/gift_sessions_controller.rb
  app/javascript/controllers/gift_checkbox.js
  app/views/gift_sessions/show.html.erb
  config/routes.rb
  package.json
  yarn.lock
Labels: enhancement

#31 Upload profile photo feat
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  app/views/pages/home.html.erb
  config/environments/development.rb
  config/storage.yml
  db/migrate/20210925121935_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: enhancement

#32 navbar styling
  app/assets/images/blank-profile-picture.png
  app/assets/images/logo.png
  app/assets/stylesheets/components/_avatar.scss
  app/assets/stylesheets/components/_navbar.scss
  app/views/devise/registrations/edit.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/shared/_navbar.html.erb
  db/seeds.rb
Labels: enhancement

#33 add container to log in & edit profile page
  app/assets/stylesheets/components/_avatar.scss
  app/assets/stylesheets/components/_form.scss
  app/assets/stylesheets/pages/_edit_user.scss
  app/assets/stylesheets/pages/_index.scss
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
Labels: enhancement

#34 Landing page
  app/assets/stylesheets/components/_friend.scss
  app/assets/stylesheets/components/_home.scss
  app/assets/stylesheets/components/_index.scss
  app/javascript/packs/application.js
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
  package.json
  yarn.lock
Labels: enhancement

#36 fixed scrollTo stimulus
  app/javascript/controllers/index.js
  app/javascript/controllers/scroll_to.js
  app/javascript/packs/application.js
  package.json
  yarn.lock
Labels: bug

#37 Question answer models
  Gemfile.lock
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_questions.scss
  app/controllers/answers_controller.rb
  app/controllers/questions_controller.rb
  app/controllers/response_sets_controller.rb
  app/models/answer.rb
  app/models/question.rb
  app/models/response_set.rb
  app/models/user.rb
  app/views/answers/create.html.erb
  app/views/questions/show.html.erb
  app/views/response_sets/edit.html.erb
  app/views/response_sets/index.html.erb
  app/views/response_sets/update.html.erb
  config/routes.rb
  db/migrate/20210925142748_drop_questionandanswersets_and_answers_tables.rb
  db/migrate/20210925142752_drop_questions.rb
  db/migrate/20210925142754_create_questions.rb
  db/migrate/20210925142912_create_answers.rb
  db/migrate/20210925144501_create_response_sets.rb
  db/migrate/20210926041047_add_parent_and_dependency_columns_to_questions.rb
  db/migrate/20210926074447_change__column_name_options_in_answers.rb
  db/migrate/20210926132729_change_choice_column_type_for_answers.rb
  db/questions_dataset/questions.json
  db/schema.rb
  db/seeds.rb
  sible_questions = @all_questions.reject do |question|
  sible_questions.reject do |question|
  sible_questions.reject! do |question|
  test/controllers/answers_controller_test.rb
  test/controllers/questions_controller_test.rb
  test/controllers/response_sets_controller_test.rb
  test/models/answer_test.rb
  test/models/question_answer_set_test.rb
  test/models/question_test.rb
  test/models/response_set_test.rb
Labels: enhancement

#38 Fix review seeds
  Gemfile.lock
  db/migrate/20210926155555_remove_friendship_association_from_reviews.rb
  db/migrate/20210926160451_remove_friendship_id_from_reviews.rb
  db/migrate/20210926160721_add_foreign_key_to_reviews.rb
  db/schema.rb
  db/seeds.rb
Labels: bug

#39 fix schema bug
  db/migrate/20210925142748_drop_questionandanswersets_and_answers_tables.rb
  db/migrate/20210925142752_drop_questions.rb
  db/schema.rb
Labels: bug

#40 moved all stimulus to application file
  app/javascript/controllers/gift_checkbox.js
  app/javascript/controllers/scroll_to.js
  app/javascript/packs/application.js
  db/schema.rb
Labels: bug

#46 Select gifts via checkbox
  app/assets/stylesheets/components/_gift_card.scss
  app/controllers/gift_sessions_controller.rb
  app/javascript/controllers/check_all_checkboxes_controller.js
  app/views/gift_sessions/show.html.erb
  config/routes.rb
Labels: enhancement

#48 Filter budget 2
  app/controllers/gift_sessions_controller.rb
  app/javascript/plugins/init_Slider.js
  app/views/gift_sessions/show.html.erb
  config/routes.rb
  package.json
  yarn.lock
Labels: bug

#49 Stripe v1 / Budget filter for gift reco
  Gemfile
  Gemfile.lock
  app/controllers/orders_controller.rb
  app/views/gift_sessions/show.html.erb
  config/initializers/money.rb
  config/initializers/stripe.rb
  config/routes.rb
  test/controllers/orders_controller_test.rb
Labels: enhancement

#50 Stripe V2
  Gemfile
  Gemfile.lock
  app/controllers/orders_controller.rb
  app/controllers/payments_controller.rb
  app/models/order.rb
  app/views/orders/show.html.erb
  app/views/payments/new.html.erb
  config/routes.rb
  test/controllers/payments_controller_test.rb
Labels: enhancement

#52 Clearing up amazon dbs
  db/amazon_datasets/video_games.json
Labels: enhancement

#53 Shopping cart feat
  app/assets/stylesheets/components/_cart.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_fonts.scss
  app/controllers/application_controller.rb
  app/controllers/carts_controller.rb
  app/controllers/line_items_controller.rb
  app/controllers/products_controller.rb
  app/javascript/controllers/quantity_controller.js
  app/models/cart.rb
  app/models/line_item.rb
  app/models/product.rb
  app/views/carts/show.html.erb
  app/views/gift_sessions/show.html.erb
  app/views/products/edit.html.erb
  app/views/products/index.html.erb
  app/views/products/new.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20210927025654_create_line_items.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/carts_controller_test.rb
  test/controllers/line_items_controller_test.rb
  test/controllers/products_controller_test.rb
  test/models/line_item_test.rb
Labels: enhancement

#55 Sports and outdoor datasets
  db/amazon_datasets/sports_outdoors.json
Labels: enhancement

#56 Fashion dataset
  db/amazon_datasets/fashion.json
Labels: enhancement

#59 remove seeds and remove merging syntax
  db/seeds.rb
  yarn.lock
Labels: bug

#61 Home kitchen data
  db/amazon_datasets/electronics.json
  db/amazon_datasets/home_kitchen.json
  db/amazon_datasets/sports_outdoors.json
Labels: enhancement

#62 Stripe payment
  app/controllers/application_controller.rb
  app/controllers/gift_sessions_controller.rb
  app/controllers/line_items_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/payments_controller.rb
  app/javascript/controllers/check_all_checkboxes_controller.js
  app/javascript/controllers/quantity_controller.js
  app/models/cart.rb
  app/models/gift_recommendation.rb
  app/models/order.rb
  app/models/product.rb
  app/models/user.rb
  app/services/stripe_checkout_session_service.rb
  app/views/carts/show.html.erb
  app/views/friendships/show.html.erb
  app/views/gift_sessions/show.html.erb
  app/views/orders/show.html.erb
  app/views/payments/new.html.erb
  app/views/shared/_navbar.html.erb
  config/environments/development.rb
  config/initializers/money.rb
  config/initializers/stripe.rb
  config/routes.rb
  db/migrate/20210928032830_monetize_product.rb
  db/migrate/20210928061005_add_user_and_cart_ref_to_order.rb
  db/migrate/20210928062032_add_state_amount_checkout_session_to_order.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#63 landing page nav bar
  app/assets/stylesheets/components/_navbar.scss
  app/controllers/pages_controller.rb
  app/views/layouts/landing_page.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#64 footer
  app/assets/images/logo-white.png
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_index.scss
  app/views/carts/show.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_footer.html.erb
Labels: enhancement

#65 fix bugs - init star rating
  app/javascript/plugins/init_star_rating.js
Labels: bug

#66 Budget filter and ratings model
  , 
  app/controllers/gift_sessions_controller.rb
  app/controllers/rating_controller.rb
  app/models/order.rb
  app/models/product.rb
  app/models/rating.rb
  db/amazon_datasets/all_beauty.json
  db/migrate/20210927112704_add_recipient_id_to_ratings.rb
  db/migrate/20210928065620_add_average_rating_remove_asin_from_product.rb
  db/migrate/20210928075739_create_ratings.rb
  db/migrate/20210928101640_add_recipient_id_to_ratings.rb
  db/schema.rb
  db/seeds.rb
  sible_questions = @all_questions.reject do |question|
  sible_questions.reject do |question|
  sible_questions.reject! do |question|
Labels: bug, enhancement

#67 stripe_2
  app/controllers/gift_sessions_controller.rb
  app/controllers/line_items_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/payments_controller.rb
  app/javascript/controllers/quantity_controller.js
  app/models/order.rb
  app/models/user.rb
  app/views/payments/new.html.erb
  config/environments/development.rb
  config/initializers/stripe.rb
Labels: bug

#68 Response set page
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_response_set.scss
  app/controllers/friendships_controller.rb
  app/controllers/response_sets_controller.rb
  app/views/friendships/index.html.erb
  app/views/response_sets/index.html.erb
  app/views/shared/_navbar.html.erb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#69 Disco gem3
  app/controllers/gift_sessions_controller.rb
  app/models/order.rb
  app/models/product.rb
  app/models/rating.rb
  app/models/user.rb
  app/views/gift_sessions/show.html.erb
  db/migrate/20210929024144_add_user_to_ratings.rb
  db/migrate/20210929025654_remove_and_add_columns_to_ratings.rb
  db/migrate/20210929031758_create_disco_recommendations.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/setup_disco.rake
Labels: enhancement

#70 remove migrations for product and user id for ratings table
  , 
  db/migrate/20210929024144_add_user_to_ratings.rb
  db/migrate/20210929025654_remove_and_add_columns_to_ratings.rb
  db/schema.rb
  sible_questions = @all_questions.reject do |question|
  sible_questions.reject do |question|
  sible_questions.reject! do |question|
Labels: bug

#71 fix syntax errors in seeds file
  db/seeds.rb
Labels: bug

#72 Some bug fixes
  app/controllers/gift_sessions_controller.rb
  app/models/product.rb
  db/seeds.rb
Labels: bug

#73 Feat selecting occasion
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_home.scss
  app/assets/stylesheets/components/_user_card.scss
  app/controllers/application_controller.rb
  app/controllers/friendships_controller.rb
  app/controllers/gift_sessions_controller.rb
  app/javascript/packs/application.js
  app/models/gift_session.rb
  app/models/occasion.rb
  app/models/order.rb
  app/models/product.rb
  app/views/friendships/index.html.erb
  app/views/friendships/show.html.erb
  app/views/pages/home.html.erb
  db/migrate/20210928102517_add_occasion_id_to_gift_session.rb
  db/migrate/20210929023936_product_occasions.rb
  db/migrate/20210929024732_add_cover_image_to_occasions.rb
  db/migrate/20210929062703_remove_occasion_id_in_gift_session.rb
  db/migrate/20210929062816_add_occasion_reference_to_gift_session.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#74 Price filter disco gem
  app/controllers/gift_sessions_controller.rb
  app/models/order.rb
  app/models/product.rb
  app/views/gift_sessions/show.html.erb
  db/seeds.rb
  lib/tasks/setup_disco.rake
Labels: bug, enhancement

#75 remove binding pry
  app/controllers/gift_sessions_controller.rb
  app/models/product.rb
Labels: invalid

#76 Taking quiz only when user response set is empty
  app/assets/stylesheets/components/_response_set.scss
  app/controllers/friendships_controller.rb
  app/controllers/response_sets_controller.rb
  app/views/friendships/index.html.erb
  app/views/response_sets/index.html.erb
  db/schema.rb
Labels: enhancement

#77 able to filter by occasion
  app/controllers/gift_sessions_controller.rb
  app/models/occasion.rb
  app/models/product.rb
  app/models/product_occasion.rb
  app/views/gift_sessions/show.html.erb
  db/migrate/20210929083032_rename_product_occassion_to_product_occasions.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#78 Fix optimize image loading speed
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_home.scss
  app/assets/stylesheets/components/_user_card.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_fonts.scss
  app/controllers/gift_sessions_controller.rb
  app/views/friendships/show.html.erb
  app/views/pages/home.html.erb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#80 gift received flow
  app/assets/stylesheets/components/_gift_card.scss
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/assets/stylesheets/config/_colors.scss
  app/controllers/gift_sessions_controller.rb
  app/controllers/products_controller.rb
  app/models/cart.rb
  app/models/gift_session.rb
  app/models/line_item.rb
  app/models/order.rb
  app/models/product.rb
  app/models/user.rb
  app/views/carts/show.html.erb
  app/views/friendships/index.html.erb
  app/views/gift_sessions/show.html.erb
  app/views/layouts/application.html.erb
  app/views/products/gift_received.html.erb
  config/environments/development.rb
  config/routes.rb
  db/seeds.rb
Labels: enhancement

#81 changed fonts and colours
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_home.scss
  app/assets/stylesheets/components/_user_card.scss
  app/assets/stylesheets/config/_colors.scss
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#83 Filter by user preferences
  app/controllers/answers_controller.rb
  app/controllers/gift_sessions_controller.rb
  app/models/product.rb
  app/views/gift_sessions/show.html.erb
  db/amazon_datasets/all_beauty.json
  db/amazon_datasets/fashion.json
  db/migrate/20210928102517_add_occasion_id_to_gift_session.rb
  db/migrate/20210929062703_remove_occasion_id_in_gift_session.rb
  db/migrate/20210929101806_add_subcat_to_answer.rb
  db/migrate/20210929105458_add_subcat_to_questions.rb
  db/migrate/20210929153928_add_subcat_to_products.rb
  db/questions_dataset/questions.json
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#82 Fix birthday reminder
  app/controllers/friendships_controller.rb
  app/views/birthdays/index.html.erb
  app/views/friendships/requests.html.erb
  db/schema.rb
Labels: bug

#85 add edge case for gift recomms
  app/models/product.rb
Labels: bug, enhancement

#86 recipient flow 2
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_gift_card.scss
  app/controllers/products_controller.rb
  app/views/gift_sessions/show.html.erb
  app/views/products/edit.html.erb
  app/views/products/gift_received.html.erb
  app/views/products/index.html.erb
  app/views/products/new.html.erb
  config/environments/development.rb
Labels: enhancement

#87 fixed home page links
  app/views/gift_sessions/show.html.erb
  app/views/pages/home.html.erb
Labels: bug

#88 Fix css 2
  app/assets/stylesheets/components/_card_product.scss
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_friend.scss
  app/assets/stylesheets/components/_home.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_friend_index.scss
  app/controllers/friendships_controller.rb
  app/views/friendships/index.html.erb
  app/views/friendships/requests.html.erb
  app/views/layouts/landing_page.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#89 General CSS (flash alert, search bar)
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components/_response_set.scss
  app/controllers/friendships_controller.rb
  app/views/birthdays/index.html.erb
  app/views/friendships/index.html.erb
  app/views/friendships/requests.html.erb
  app/views/friendships/search.html.erb
  app/views/gift_sessions/show.html.erb
  db/schema.rb
Labels: enhancement

#90 fix seed bugs
  app/controllers/gift_sessions_controller.rb
  app/models/product.rb
  app/views/gift_sessions/show.html.erb
  db/migrate/20210930032523_remove_product_from_order.rb
  db/schema.rb
  db/seeds.rb
Labels: bug

#91 Fix css 3
  app/assets/stylesheets/components/_card_product.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/pages/_friend_index.scss
  app/views/friendships/index.html.erb
  app/views/products/gift_received.html.erb
  db/schema.rb
Labels: enhancement

#92 Fix friend profile css
  app/assets/stylesheets/pages/_friend_index.scss
  app/controllers/friendships_controller.rb
  app/views/birthdays/index.html.erb
  app/views/friendships/index.html.erb
  app/views/friendships/requests.html.erb
  app/views/friendships/search.html.erb
  app/views/shared/_friend-side-panel.html.erb
Labels: enhancement

#93 Birth year at user sign up / edit profile
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/friendships/index.html.erb
  app/views/friendships/requests.html.erb
  db/schema.rb
Labels: bug

#94 add last and username to pg search scope
  app/assets/stylesheets/config/_colors.scss
  app/models/user.rb
Labels: enhancement

#95 Fix friends index css
  app/assets/stylesheets/components/_card_product.scss
  app/assets/stylesheets/components/_footer.scss
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/components/_user_card.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/pages/_friend_index.scss
  app/views/friendships/index.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/landing_page.html.erb
  app/views/products/gift_received.html.erb
  app/views/shared/_friend-side-panel.html.erb
  app/views/shared/_navbar.html.erb
  db/schema.rb
Labels: enhancement

#96 Diff view if no upcoming birthday
  app/controllers/birthdays_controller.rb
  app/views/birthdays/index.html.erb
Labels: enhancement

#99 style ratings page
  app/assets/stylesheets/pages/_rating.scss
Labels: bug

#100 edit landing page
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_home.scss
  app/views/pages/home.html.erb
Labels: enhancement

#101 amend friends index styling
  app/assets/stylesheets/pages/_friend_index.scss
Labels: enhancement

#103 Friends index sidebar
  app/assets/stylesheets/pages/_friend_index.scss
Labels: enhancement

#104 Fix gift session css
  app/assets/stylesheets/components/_gift_card.scss
  app/assets/stylesheets/components/_user_card.scss
  app/views/friendships/index.html.erb
  app/views/gift_sessions/show.html.erb
Labels: enhancement

#105 Recipient flow 2
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_gift_card.scss
  app/controllers/orders_controller.rb
  app/controllers/products_controller.rb
  app/controllers/rating_controller.rb
  app/models/order.rb
  app/views/gift_sessions/show.html.erb
  app/views/layouts/application.html.erb
  app/views/products/gift_received.html.erb
  app/views/rating/new.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#106 Friend request page css
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/pages/_friend_request.scss
  app/views/friendships/requests.html.erb
Labels: enhancement

#107 Question page css
  app/assets/stylesheets/components/_response_set.scss
  app/assets/stylesheets/pages/_questions.scss
  app/views/questions/show.html.erb
  db/schema.rb
Labels: enhancement

#108 style multiple elements across friends index, birthday, friends side panel and search results
  app/assets/stylesheets/components/_card_product.scss
  app/assets/stylesheets/pages/_friend_index.scss
  app/assets/stylesheets/pages/_friend_request.scss
  app/views/birthdays/index.html.erb
  app/views/friendships/index.html.erb
  app/views/friendships/requests.html.erb
  app/views/shared/_friend-side-panel.html.erb
Labels: enhancement

#109 Footer css
  app/assets/stylesheets/components/_footer.scss
  db/schema.rb
Labels: enhancement

#110 Amend navbar routing and styling
  app/assets/stylesheets/components/_avatar.scss
  app/views/friendships/requests.html.erb
  app/views/layouts/landing_page.html.erb
  app/views/shared/_navbar.html.erb
Labels: bug, enhancement

#111 Fix user edit profile css
  app/assets/stylesheets/pages/_edit_user.scss
  app/views/devise/registrations/edit.html.erb
Labels: bug

#112 fix gift received page
  app/controllers/application_controller.rb
  app/controllers/products_controller.rb
  app/models/gift_session.rb
  app/models/order.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  app/views/friendships/search.html.erb
  app/views/friendships/show.html.erb
  app/views/products/gift_received.html.erb
  db/migrate/20210930110113_add_description_to_user.rb
  db/schema.rb
Labels: bug

#113 Fix shopping cart css
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_cart.scss
  app/assets/stylesheets/components/_cart2.scss
  app/views/carts/show.html.erb
  db/schema.rb
Labels: enhancement

#115 fix_gift_received_bug
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#116 fixed total at checkout page
  app/assets/stylesheets/components/_cart.scss
  app/assets/stylesheets/components/_cart2.scss
  app/controllers/orders_controller.rb
  app/views/carts/show.html.erb
  app/views/payments/new.html.erb
Labels: enhancement

#117 added favicon
  app/assets/images/favicon.ico
  app/views/layouts/application.html.erb
  db/schema.rb
Labels: enhancement

#121 Response set index2
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_cart.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/pages/_questions.scss
  app/assets/stylesheets/pages/_response_set.scss
  app/views/carts/show.html.erb
  app/views/questions/show.html.erb
  app/views/response_sets/index.html.erb
Labels: bug, enhancement

#120 Landing page video
  app/assets/stylesheets/pages/_home.scss
  app/views/pages/home.html.erb
Labels: enhancement

#118 Set up meta tags
  app/assets/config/initializers/default_meta.rb
  app/assets/config/meta.yml
  app/helpers/meta_tags_helper.rb
  app/views/layouts/application.html.erb
Labels: enhancement
