Repository Mashiepotatoes/SurpriseMe, pull requests merged in 2021-10, with the labels that each got.

#122 fixed footer at paid page & fixed empty cart show page
  app/assets/stylesheets/pages/_home.scss
  app/helpers/meta_tags_helper.rb
  app/views/carts/show.html.erb
  app/views/layouts/application.html.erb
  app/views/orders/show.html.erb
Labels: enhancement

#123 added desc & image to db
  db/amazon_datasets/all_beauty.json
Labels: enhancement

#124 delete extra migration that adds recipient id to ratings table
  db/migrate/20210928101640_add_recipient_id_to_ratings.rb
Labels: bug

#125 Gift received page css
  app/assets/stylesheets/components/_gift_card.scss
  app/assets/stylesheets/pages/_friend_profile.scss
  app/controllers/application_controller.rb
  app/controllers/orders_controller.rb
  app/models/cart.rb
  app/models/line_item.rb
  app/models/order.rb
  app/models/user.rb
  app/services/stripe_checkout_session_service.rb
  app/views/birthdays/index.html.erb
  app/views/carts/show.html.erb
  app/views/friendships/index.html.erb
  app/views/friendships/requests.html.erb
  app/views/friendships/show.html.erb
  app/views/products/gift_received.html.erb
  config/environments/development.rb
  config/routes.rb
  db/migrate/20211001020116_add_status_to_line_items.rb
  db/schema.rb
Labels: enhancement

#127 Feat noti
  .env.sample
  Gemfile
  Gemfile.lock
  app/controllers/friendships_controller.rb
  app/mailers/application_mailer.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/shared/_friend-side-panel.html.erb
  app/views/user_mailer/sent_gift.html.erb
  app/views/user_mailer/sent_gift.text.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/smtp.rb
  config/routes.rb
  test/mailers/previews/user_mailer_preview.rb
  test/mailers/user_mailer_test.rb
Labels: enhancement

#128 General css fix
  app/assets/stylesheets/pages/_home.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_user-signin.scss
  app/assets/stylesheets/pages/_user-signup.scss
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  app/views/rating/new.html.erb
  db/schema.rb
Labels: bug

#129 mailer bug fixed
  app/controllers/friendships_controller.rb
  app/models/user.rb
  app/services/stripe_checkout_session_service.rb
  config/environments/development.rb
  db/schema.rb
Labels: bug

#130 fixed cloudinary
  config/environments/production.rb
Labels: bug

#132 changed flash notice route
  app/controllers/orders_controller.rb
  app/services/stripe_checkout_session_service.rb
Labels: bug

#133 Fix the width of edit response pink button
  app/assets/stylesheets/pages/_response_set.scss
  app/views/response_sets/index.html.erb
  db/schema.rb
Labels: bug

#134 Fix mailer flash 2
  app/assets/stylesheets/components/_button.scss
  app/assets/stylesheets/components/_cart.scss
  app/controllers/orders_controller.rb
  app/services/stripe_checkout_session_service.rb
  app/views/friendships/show.html.erb
  app/views/orders/show.html.erb
  app/views/user_mailer/sent_gift.html.erb
  db/schema.rb
Labels: bug, enhancement

#135 Side panel color if selected, birthday index sorted by days
  app/assets/stylesheets/components/_card_product.scss
  app/assets/stylesheets/pages/_birthday.scss
  app/assets/stylesheets/pages/_friend_index.scss
  app/assets/stylesheets/pages/_index.scss
  app/controllers/birthdays_controller.rb
  app/views/birthdays/index.html.erb
  app/views/shared/_friend-side-panel.html.erb
Labels: enhancement

#136 fixed image url
  app/assets/stylesheets/components/_gift_card.scss
  app/views/gift_sessions/show.html.erb
  db/amazon_datasets/all_beauty.json
  db/amazon_datasets/fashion.json
  db/seeds.rb
Labels: bug

#139 Exit preference route
  app/controllers/questions_controller.rb
  app/controllers/response_sets_controller.rb
  app/models/user.rb
  app/views/questions/landing.html.erb
  app/views/questions/show.html.erb
  app/views/response_sets/index.html.erb
  app/views/shared/_friend-side-panel.html.erb
  config/routes.rb
  e
Labels: bug, enhancement

#138 comment out conditional statement for disco gem curate class method
  app/assets/stylesheets/components/_card_product.scss
  app/assets/stylesheets/components/_friend.scss
  app/assets/stylesheets/pages/_response_set.scss
  app/models/product.rb
Labels: bug

#137 Landing page edits
  app/assets/stylesheets/components/_navbar.scss
  app/assets/stylesheets/pages/_home.scss
  app/views/pages/home.html.erb
Labels: enhancement

#140 Various fixes
  app/controllers/gift_sessions_controller.rb
  app/controllers/rating_controller.rb
  app/views/gift_sessions/show.html.erb
  app/views/products/gift_received.html.erb
  app/views/rating/new.html.erb
  config/routes.rb
  db/seeds.rb
  quit
Labels: bug

#141 Pref quiz css
  app/assets/stylesheets/pages/_questions.scss
  app/views/questions/show.html.erb
  db/schema.rb
Labels: enhancement

#142 Remove sent gift / edit response btn
  app/assets/stylesheets/pages/_response_set.scss
  app/views/response_sets/index.html.erb
  app/views/shared/_friend-side-panel.html.erb
Labels: bug

#143 use new datasets for dmo
  app/models/product.rb
  app/views/rating/new.html.erb
  db/amazon_datasets/demo_set_beauty.json
  db/amazon_datasets/demo_set_fashion.json
  db/seeds.rb
Labels: bug

#148 friend-request-btn
  app/assets/stylesheets/pages/_questions.scss
Labels: bug

#149 fix disco recommendations
  app/models/product.rb
  db/amazon_datasets/demo_set_beauty.json
  db/seeds.rb
  e
  lib/tasks/setup_disco.rake
Labels: bug
